WIP: Patch RPATHs of non-Python extension dependencies
pypa/auditwheel pull request #283
Opened 2021-02-06 20:06 UTC by bdice

This PR aims to resolve issue #136, and will replace PR #139.

I'm opening this draft PR to run CI checks while I finish testing things locally. I'll update this description when it's ready for review.

Summary of the problem:
> We have a few Python extensions that link to `libfreud.so` and `libtbb.so`, neither of which are Python extensions. `libfreud.so` is also linked to `libtbb.so`. auditwheel correctly relocates the RPATHs of our Python extensions, but does not alter the RPATH of `libfreud.so` to point to the relocated `libtbb.so`.

2021-02-06 23:18 UTC, bdice commented on auditwheel/wheel_abi.py
> +                nonpy_elftree[fn], ctx.path)
The core of the fix is just to move this line out of the "if" statement above.

2021-02-07 20:06 UTC, thomaslima commented
Thank you so much for providing this. I really wasn't able to work on the original PRs. I wonder if you have used any of the code that I wrote for this.

2021-02-07 20:24 UTC, bdice commented
> Thank you so much for providing this. I really wasn't able to work on the original PRs. I wonder if you have used any of the code that I wrote for this.

Yes, I based this on your previous PRs. You can see in the commit history that I cherry-picked your previous work onto a new branch before updating the code, so that you receive credit in the git history. 👍

2021-02-07 20:28 UTC, mayeut commented
Thanks for working on this @bdice, @thomaslima 
I will review this next week-end at the latest.

2021-02-14 14:19 UTC, mayeut requested changes
The functional code change is OK however, I find the test case a bit too complicated and might conflict (or more exactly, the test would become useless) with #152 

A simpler, more contained test should work as well here, maybe something like `tests/integration/testdependencies` but going one level deeper in dependencies to cover the issue would work if I understand correctly ?

2021-02-16 03:09 UTC, bdice commented
@mayeut I agree that your suggestion for a simpler test extension would be good. I had hoped it would be good enough as-is, but you're right that won't work any more with #152. It will take me some time to make these changes -- I will try to have a simpler test extension by the end of the week. Is there a release schedule or other timeline to be aware of? I would like to get this fix into the next release if possible.

2021-02-19 18:53 UTC, psavery commented
@bdice Thanks for working on this. I can confirm this fixes #136 for us.

Until it's in a release, we'll patch this change into the docker image we're using with cibuildwheel.

2021-02-22 06:07 UTC, bdice commented
Update: I just finished writing a new, simpler test case. I have to do some local testing and code cleanup before re-requesting review. I anticipate having updated tests for this PR finished in the next 2 days.

2021-02-22 07:43 UTC, mayeut commented
Thanks for the update @bdice 
> Is there a release schedule or other timeline to be aware of? I would like to get this fix into the next release if possible.

We have no release schedule for `auditwheel`. Given this fixes an issue, I'd plan to release `auditwheel` at most 1 week after merging the PR depending on my free time to do so. The other PRs are not blocker for a release.

2021-02-22 19:56 UTC, bdice commented
@mayeut I tried to create a new test, in `tests/integration/test_nonpy_dependencies`, but it's not catching the problem correctly (the tests pass without the fix). I had to learn the Python C API and a lot of gcc linker behaviors that I haven't dealt with before, and it looks like I didn't quite get the "failing case" correct. Maybe I can use the previous test infrastructure but just use another external library that isn't `zlib`? Would that fix the conflict with #152 and be alright with you as a maintainer? Do you have a recommended library that I should try to use? I appreciate the help.

2021-02-26 06:50 UTC, mayeut commented
@bdice,
Anything other than `zlib` and `expat` would be fine I think. You can probably try using symbols from `libxcrypt`, it won't be whitelisted again and can be grafted properly.

> Is it expected that auditwheel will use the oldest possible platform tag for the ABIs in the wheel, even if --plat is given a newer tag?

Yes, see also #281

2021-03-18 18:09 UTC, closed without merging