add loongarch64 platform support
pypa/auditwheel pull request #522
Opened 2024-12-20 02:19 UTC by wxpppp

When I used the auditwheel tool to repair a wheel package on the LoongArch64 Alpine platform, I encountered an error. So, I added some LoongArch64 platform-related code to support musllinux and manylinux.

PS: Alpine v3.21 has support loongarch64 platform.(https://wiki.alpinelinux.org/wiki/Loongarch64)

2024-12-31 03:27 UTC, wojiushixiaobai commented
@wxpppp 
Hello, can the code be adapted for manylinux_2_34?
It is recommended to support it from manylinux_2_31 like the riscv64 architecture.

2025-01-18 17:01 UTC, mayeut requested changes
Seems almost correct but I can't really check this.

2025-01-20 03:12 UTC, wxpppp commented on src/auditwheel/policy/manylinux-policy.json
> +        "GLIBC": ["2.36", "ABI_DT_RELR"],
Hello, thank you for reviewing the code. I have tested it on a machine with the LoongArch platform, and indeed, the symbol GLIBC_2.37 is not present in the libc.so of the corresponding version.

2025-01-20 06:25 UTC, wxpppp commented on src/auditwheel/policy/manylinux-policy.json
> +        "GLIBC": ["2.36", "ABI_DT_RELR"],
Hello, thank you for reviewing the code. I have tested it on a machine with the LoongArch platform, and indeed, the symbol GLIBC_2.37 is not present in the libc.so of the corresponding version.

2025-01-21 02:09 UTC, wxpppp commented
You can run a LoongArch container environment on an x86 machine as follows:
```
docker run --rm --privileged ghcr.io/loong64/qemu-user-static --reset -p yes
# Debian
docker run --rm --platform linux/loong64 -it ghcr.io/loong64/debian:trixie-slim bash
```

2025-01-24 04:57 UTC, mayeut commented on src/auditwheel/policy/manylinux-policy.json
> +        "GLIBC": ["2.36", "ABI_DT_RELR"],
thanks for the confirmation

2025-01-24 04:57 UTC, merged